### ISSUE TITLE
OpenMV IDE Crash On Import TinyDB

### ISSUE THREAD

**Issue by pbhuter** [openmv/openmv-ide#165]
**Describe the bug**
OpenMV IDE crashes when trying to import from tinydb

**To Reproduce**
1. Copy 'tinydb' folder and contents to OpenMV board
2. Create a blank 'tinydb' folder in OpenMV directory on PC
3. Include 'from tinydb import TinyDB, Query' at the top of .py file in IDE
4. Run .py file in IDE, causing the IDE to crash

**Expected behavior**
The IDE should run the rest of the code

**Screenshots**
![image](https://user-images.githubusercontent.com/116843937/198390819-3aacbf4f-6a8b-4c47-a392-10783f02b5b9.png)

**Please complete the following information**
 - IDE version: 2.97
 - Firmware version: unsure, but it was updated to most recent a couple days ago
 - Board: OpenMV Cam H7 R2
 - OS: Windows 10
[tinydb.zip](https://github.com/openmv/openmv/files/9882894/tinydb.zip)

**Comment by kwagyeman** [comment]
Thanks for finding this. I have duplicated the error. Fixing now.

**Comment by kwagyeman** [comment]
Found the issue. It was because my parser assumed that you'd use the module name for the file versus ".". Anyway, there was a piece of code where I'd try to grab form a list and it could be empty expecting the module name which caused the IDE to crash.

This is now fixed. I also fixed an issue with the scanner computing the wrong hash of the module given the order of files being scanned.

Thanks for find this. I don't use this feature too much and it's been broken. It should work well now.

...

As an aside. Issues with the IDE should get fixed quicker now. Trying to go full-time on OpenMV.
