### ISSUE TITLE
Why openmv-ide is NOT python 3.5 compatible?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#6]
The onboard file **main.py** seems to be fully compatible with **python 3.5.x**, while openmv-ide and openmv are **NOT**... 

Any plan to improve the compatibility?

Cheers
Pei

**Comment by kwagyeman** [comment]
OpenMV IDE doesn't care what you write. It doesn't compile anything. Right now, the syntax highlighting/auto completion need fixed in the IDE however. The plan is to tackle that after I finish updating the docs.

As for the openmv-cam. Ibrahim needs to update the version of MP we are pulling in. It's just a pain for him since this usually involves having to fix tons of compile issues.

Anyway, yes, we plan to fix all this stuff. It's not not the most pressing thing on fire right now. Finishing the website and then updating the docs are what I will be working on next.
