### ISSUE TITLE
can not install 2.4.0.exe win IDE

### ISSUE THREAD

**Issue by trackme518** [openmv/openmv-ide#73]
Hi,
 I get "Cannot open temporary file: No error" at 99% (writing maintanace tool) installation completation of 2.4.0 IDE. I am on updated WIN10 as of 26.4.2020

Details:
Preparing the installation...

Installing component OpenMV IDE Application...
Extracting "2.4.0openmv-ide-windows-2.4.0-installer-archive.7z"
Done
Writing maintenance tool. <-this is where it fails

Installation aborted!

**Comment by kwagyeman** [comment]
Not sure how to help you. This isn't reproduce-able. Also, the installer is generated by the Qt installer framework. I don't control how that binary writes data.

I can imagine however that the issue is with your system versus an error with OpenMV IDE. If the installer fails to write data... could you be running out of space?
